shared_preload_libraries = 'timescaledb, pg_cron'

# Network
listen_addresses = '*'

# Auth
ssl = on
ssl_cert_file = '/etc/postgresql/ssl/postgres.crt'
ssl_key_file = '/etc/postgresql/ssl/postgres.key'
ssl_ca_file = '/etc/postgresql/ssl/root_ca.crt'
hba_file = '/etc/postgresql/pg_hba.conf'
ident_file = '/etc/postgresql/pg_ident.conf'

# Cron
cron.database_name = 'ekaine'