shared_preload_libraries = 'timescaledb, pg_cron, pg_stat_statements'

# Network
listen_addresses = '*'

# Auth
ssl = on
ssl_cert_file = '/etc/postgresql/ssl/postgres.crt'
ssl_key_file = '/etc/postgresql/ssl/postgres.key'
ssl_ca_file = '/etc/postgresql/ssl/root_ca.crt'
hba_file = '/etc/postgresql/pg_hba.conf'
ident_file = '/etc/postgresql/pg_ident.conf'

# Cron
cron.database_name = 'ekaine'

# Stat Statements
pg_stat_statements.max = 25000 # Max statements to track
pg_stat_statements.track = all # 'all' to include nested/internal
pg_stat_statements.track_utility = on
pg_stat_statements.save = on
