##################### Server #####################
[server]
# The public-facing URL of your Grafana instance
# must match exactly what you register in Discord redirect URIs
# root_url = "https://grafana.ekaine.space"
root_url = "http://localhost:3000"
serve_from_sub_path = false

##################### Security ####################
[security]
# Disable Grafana’s own login form (only Discord SSO)
disable_login_form = true
# Disable anonymous access
allow_anonymous = false

############## Session / Cookie ##############
[session]
# ensure cookie is HTTPS-only and SameSite Lax (required for redirect flow)
cookie_secure = true
cookie_samesite = lax

############## Token Rotation ##############
[auth]
token_rotation_interval_minutes = 60

login_maximum_lifetime_duration = 30d
login_maximum_inactive_lifetime_duration = 24h

[auth.proxy]
enabled = true
# HTTP Header name that will contain the username or email
header_name = X-Forwarded-Discord-Username
# HTTP Header property, defaults to `username` but can also be `email`
header_property = username
# Set to `true` to enable auto sign up of users who do not exist in Grafana DB. Defaults to `true`.
auto_sign_up = true
# Define cache time to live in minutes
# If combined with Grafana LDAP integration it is also the sync interval
# Set to 0 to always fetch and sync the latest user data
sync_ttl = 0
# Limit where auth proxy requests come from by configuring a list of IP addresses.
# This can be used to prevent users spoofing the X-WEBAUTH-USER header.
# Example `whitelist = 192.168.1.1, 192.168.1.0/24, 2001::23, 2001::0/120`
#
# This CIDR is configured via docker-compose.yaml - ekaine_net's CIDR is hardcoded.
whitelist = 172.66.0.0/16
# Optionally define more headers to sync other user attributes
# Example `headers = Name:X-WEBAUTH-NAME Role:X-WEBAUTH-ROLE Email:X-WEBAUTH-EMAIL Groups:X-WEBAUTH-GROUPS`
headers =
# Non-ASCII strings in header values are encoded using quoted-printable encoding
;headers_encoded = false
# Check out docs on this for more details on the below setting
enable_login_token = false

[database]
type = postgres
# Grafana <-> PG talk over internal docker network
url = postgres://ekaine:ekaine_pw@ekaine_db:5432/grafana_meta?sslmode=disable

[panels]
enable_alpha = true

[plugins]
preinstall = ["volkovlabs-table-panel", "volkovlabs-variable-panel", "marcusolsson-dynamictext-panel"]
