[server]
root_url = "https://grafana.ekaine.space"

[database]
type = postgres
# Grafana <-> PG talk over internal docker network
url = postgres://ekaine:ekaine_pw@postgres:5432/ekaine?sslmode=disable

[panels]
enable_alpha = true

[plugins]
preinstall = ["volkovlabs-table-panel", "volkovlabs-variable-panel", "marcusolsson-dynamictext-panel"]
