"""Add Mining Maps and Farmable Cores

Revision ID: 75792b281582
Revises: 33ea35e672c1
Create Date: 2025-06-19 14:31:10.152577

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75792b281582"
down_revision: str | None = "33ea35e672c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "binary_data",
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="core",
    )
    op.create_table(
        "farmable_cores",
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("body_id", sa.Integer(), nullable=False),
        sa.Column("hotspot_id", sa.Integer(), nullable=False),
        sa.Column("commodity_sym", sa.Text(), nullable=False),
        sa.Column("hotspot_from_sc_img", sa.Integer(), nullable=False),
        sa.Column("core_from_drop_img", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["body_id"],
            ["core.bodies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["commodity_sym"],
            ["core.commodities.symbol"],
        ),
        sa.ForeignKeyConstraint(
            ["core_from_drop_img"],
            ["core.binary_data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hotspot_from_sc_img"],
            ["core.binary_data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hotspot_id"],
            ["core.hotspots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["core.systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("system_id", "body_id", "hotspot_id", "commodity_sym", name="_farmable_cores_uc"),
        schema="core",
    )
    op.create_table(
        "mining_maps",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("body_id", sa.Integer(), nullable=False),
        sa.Column("hotspot_id", sa.Integer(), nullable=False),
        sa.Column("rock_count", sa.SmallInteger(), nullable=False),
        sa.Column("map_url", sa.Text(), nullable=False),
        sa.Column("approximate_merits_solo", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["body_id"],
            ["core.bodies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hotspot_id"],
            ["core.hotspots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["core.systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("system_id", "body_id", "hotspot_id", "name", name="_mining_map_uc"),
        schema="core",
    )
    op.create_table(
        "mining_map_commodities",
        sa.Column("mining_map_id", sa.Integer(), nullable=False),
        sa.Column("commodity_sym", sa.Text(), nullable=False),
        sa.Column("approximate_tonnage_solo", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commodity_sym"],
            ["core.commodities.symbol"],
        ),
        sa.ForeignKeyConstraint(
            ["mining_map_id"],
            ["core.mining_maps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mining_map_id", "commodity_sym", name="_mining_map_commodities_uc"),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mining_map_commodities", schema="core")
    op.drop_table("mining_maps", schema="core")
    op.drop_table("farmable_cores", schema="core")
    op.drop_table("binary_data", schema="core")
    # ### end Alembic commands ###
