"""Add initial monitoring tsdb hypertables

Revision ID: 40976b15c3d7
Revises: cc0b3ea98d92
Create Date: 2025-06-10 01:52:57.496193

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from ekaine.common.constants import SQL_DIR

functions_sql_dir = SQL_DIR / "functions"

# revision identifiers, used by Alembic.
revision: str = "40976b15c3d7"
down_revision: str | None = "cc0b3ea98d92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("create schema if not exists monitoring")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hypertable_sizes",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("schema_name", sa.String(), nullable=False),
        sa.Column("table_name", sa.String(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("row_estimate", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "timestamp"),
        schema="monitoring",
    )
    op.drop_table("systems", schema="timescaledb")
    op.drop_table("signals", schema="timescaledb")
    op.drop_table("market_commodity_faction_state", schema="timescaledb")
    # ### end Alembic commands ###

    op.create_unique_constraint(
        "_monitoring_ht_sizes_schm_tbl_n_ts_uc",
        "hypertable_sizes",
        ["schema_name", "table_name", "timestamp"],
        schema="monitoring",
    )
    op.execute(
        "select create_hypertable(" "'monitoring.hypertable_sizes', by_range('timestamp'), if_not_exists => true);"
    )

    with open(functions_sql_dir / "monitoring_insert_tsdb_hypertable_sizes_v1.sql") as f:
        op.execute(f.read())

    every = 15  # minutes
    op.execute(
        "SELECT cron.schedule('insert_tsdb_hypertable_sizes', "
        f"'*/{every} * * * *', $$CALL monitoring.insert_tsdb_hypertable_sizes('{every} minutes');$$);"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("SELECT cron.unschedule('insert_tsdb_hypertable_sizes')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_commodity_faction_state",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("system_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("sy_cf_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("sy_cf_state", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("sy_cf_active_states", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
        sa.Column("station_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("st_cf_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("st_cf_state", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("st_cf_active_states", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
        sa.Column("commodity_sym", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("sell_price_multiplier", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("buy_price_multiplier", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", "timestamp", name="market_commodity_faction_state_pkey"),
        schema="timescaledb",
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("system_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("signal_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("signal_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_station", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("uss_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("spawning_state", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("spawning_faction", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("spawning_power", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("opposing_power", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("threat_level", sa.SMALLINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", "timestamp", name="signals_pkey"),
        schema="timescaledb",
    )
    op.create_table(
        "systems",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("system_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("allegiance", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("population", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("primary_economy", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("secondary_economy", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("security", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("government", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("controlling_faction_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("controlling_power", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "power_conflict_progress", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("power_state", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "power_state_control_progress", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column("power_state_reinforcement", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("power_state_undermining", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("powers", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("is_backfilled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", "timestamp", name="systems_pkey"),
        schema="timescaledb",
    )
    op.drop_table("hypertable_sizes", schema="monitoring")
    # ### end Alembic commands ###

    op.execute("drop schema if exists monitoring cascade")
