---
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "10"

x-ekaine-envvars: &ekaine_envvars
  REDIS_DSN: "redis://ekaine_redis:6379/0"
  GRAFANA_URL: "http://ekaine_grafana:3000"
  EKAINE_DATABASE_URL: "postgresql://ekaine:ekaine_pw@ekaine_db:5432/ekaine"
  GRAFANA_DATABASE_URL: "postgresql://ekaine:ekaine_pw@ekaine_db:5432/grafana_meta"
  DISCORD_REDIRECT_URI: "${EKAINE_ROOT_URL}/oauth2/callback"
  DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
  DISCORD_CLIENT_ID: "${DISCORD_CLIENT_ID}"
  DISCORD_CLIENT_SECRET: "${DISCORD_CLIENT_SECRET}"
  COOKIE_SECRET: "${COOKIE_SECRET}"

x-app: &ekaine_app
  image: remiscarlet/ekaine
  stdin_open: true
  tty: true
  environment: *ekaine_envvars
  networks: [ekaine_net]
  volumes:
    - ../../tools/:/app/tools
    - ../../src/:/app/src
    - ../../Makefile:/app/Makefile
    - ../../app_logs:/app/app_logs
  logging: *default-logging

services:
  postgres:
    container_name: ekaine_db
    image: timescale/timescaledb-ha:pg17
    restart: always
    shm_size: 2g
    environment:
      POSTGRES_USER: ekaine
      POSTGRES_PASSWORD: ekaine_pw
      POSTGRES_DB: ekaine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "ekaine", "-d", "ekaine"]
      interval: 10s
      timeout: 10s
      retries: 15
    ports: ["${PG_PORT:-5432}:5432"]
    networks: [ekaine_net]
    volumes:
      - pg-data-hostfs:/home/postgres/pgdata
      - ./ekaine_ca/certs:/etc/postgresql/ssl:ro
      - ./timescaledb/scripts/015_add-grafana.sql:/docker-entrypoint-initdb.d/015_add-grafana.sql
      - ./timescaledb/scripts/020_fix-perms.sh:/docker-entrypoint-initdb.d/020_fix-perms.sh
      - ./timescaledb/conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./timescaledb/conf/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./timescaledb/conf/pg_ident.conf:/etc/postgresql/pg_ident.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    logging: *default-logging

  grafana:
    container_name: ekaine_grafana
    image: grafana/grafana-enterprise
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "${DISCORD_CLIENT_ID}"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "${DISCORD_CLIENT_SECRET}"
    expose: ["3000"]
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/access-control:/etc/grafana/provisioning/access-control
    networks: [ekaine_net]
    logging: *default-logging

  redis:
    container_name: ekaine_redis
    image: redis:8-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks: [ekaine_net]
    logging: *default-logging

  smallstep-ca:
    image: remiscarlet/ekaine_ca
    container_name: ekaine_ca
    ports: ["${SMALLSTEP_PORT:-9000}:9000"] # CA API
    environment:
      - DOCKER_STEPCA_INIT_NAME=ekaine-ca
      - DOCKER_STEPCA_INIT_DNS_NAMES=localhost,ca.ekaine.space
      - DOCKER_STEPCA_INIT_PASSWORD_FILE=/home/step/secrets/password.txt
    volumes:
      - ./ekaine_ca/config:/home/step/config
      - ./ekaine_ca/secrets:/home/step/secrets:ro
      - ./ekaine_ca/certs:/home/step/certs
      - ./ekaine_ca/db:/home/step/db
      - ./ekaine_ca/entrypoint.sh:/entrypoint.sh:ro
    networks: [ekaine_net]
    entrypoint: /entrypoint.sh
    logging: *default-logging

  setup:
    <<: *ekaine_app
    container_name: ekaine_setup
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["bash", "-c", "pwd && ls -al && make setup-container && make hydrate-db"]

  fastapi:
    <<: *ekaine_app
    container_name: ekaine_fastapi
    depends_on:
      postgres:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
    ports: ["8001:8001"]
    command:
      - "poetry"
      - "run"
      - "uvicorn"
      - "src.ekaine.interfaces.rest.api_handler:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8001"

  discord:
    <<: *ekaine_app
    container_name: ekaine_discord
    depends_on:
      postgres:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
    command:
    - "python"
    - "src/ekaine/interfaces/discord/bot.py"

  eddn:
    container_name: ekaine_eddn
    <<: *ekaine_app
    depends_on:
      postgres:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
    command:
    - "poetry"
    - "run"
    - "cli"
    - "ingestion"
    - "eddn-listener"

volumes:
  pg-data-hostfs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PG_DATA_PATH:-/var/lib/ekaine/postgresql}"
  grafana-data:
  redis-data:

networks:
  ekaine_net:
    driver: bridge
    ipam:
      config:
        # Used in tools/docker/grafana/conf/grafana.ini
        - subnet: 172.66.0.0/16